Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -5,35 +5,39 @@ on:
     branches:
       - main
 
+env:
+  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
+  REMOTE_USER: ${{ secrets.REMOTE_USERNAME }}
+  REMOTE_PATH: "/var/www/TranSafe-Frontend/"
+
 jobs:
   deploy:
     runs-on: ubuntu-latest
-
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
-
-    - name: Install Dependencies
-      run: npm install
-
-    - name: Build the Project
-      run: npm run build
-
-    - name: Run rsync deploy action
-      uses: easingthemes/ssh-deploy@v3.1.1
-      with:
-        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
-        REMOTE_USER: ${{ secrets.REMOTE_USERNAME }}
-        args: -rltgoDzvO --delete --exclude=node_modules --exclude=.git --exclude=dist --exclude=.* --exclude=_* /home/runner/work/TranSafe-Frontend/TranSafe-Frontend/dist/ REMOTE_USER@REMOTE_HOST:/var/www/TranSafe-Frontend/
-
-    - name: Log rsync output
-      run: echo "${{ steps.rsync.outputs.stdout }}"
-
-    - name: Check rsync status
-      run: |
-        if [ ${{ steps.rsync.outputs.status }} -eq 0 ]; then
-          echo "Deployment successful"
-        else
-          echo "Deployment failed"
-        fi
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Install rsync
+        run: sudo apt-get -y install rsync
+      - name: Deploy over SSH
+        uses: easingthemes/ssh-deploy@v3.1.1
+        with:
+          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}
+          run: |
+            echo "✅️ [CLI] Rsync exists"
+            which rsync
+            echo "[Rsync] Starting Rsync Action: ${GITHUB_WORKSPACE} to ${env.REMOTE_USER}@${env.REMOTE_HOST}:${env.REMOTE_PATH}"
+            echo "[Rsync] excluding folders "
+            echo "- node_modules"
+            echo "- .git"
+            echo "- dist"
+            echo "- .*"
+            echo "- _*"
+            rsync -azv --delete --exclude=node_modules --exclude=.git --exclude=dist --exclude=.* --exclude=_* ${GITHUB_WORKSPACE}/ ${env.REMOTE_USER}@${env.REMOTE_HOST}:${env.REMOTE_PATH} --rsync-path="sudo rsync"
+            exit_status=$?
+            if [ $exit_status -eq 0 ]; then
+              echo "✅️ [Rsync] completed successfully."
+            else
+              echo "❌ [Rsync] error: rsync exited with code $exit_status"
+              exit $exit_status
+            fi
